services:
  - type: web
    name: backend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campaign-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: campaign-redis
          type: redis

  - type: static
    name: frontend
    buildCommand: "npm install && npm run build"
    publishPath: build

  - type: worker
    name: campaign-worker
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "node worker.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: campaign-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: campaign-redis
          type: redis

databases:
  - name: campaign-db
    plan: free

redis:
  - name: campaign-redis
    plan: free
