services:
  - type: web
    name: motionfalcon-backend
    env: python
    rootDir: crypto-backend
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://crypto-frontend-lffc.onrender.com,http://localhost:3000,http://localhost:5173"
      - key: ENVIRONMENT
        value: "production"
      - key: FORCE_REDEPLOY
        value: "true"

  - type: static
    name: crypto-frontend
    rootDir: crypto-frontend
    region: oregon
    buildCommand: "npm install && npm run build"
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://motionfalcon-backend.onrender.com"



databases:
  - name: crypto-db
    plan: free
    region: oregon

  