services:
  # ---------- Database ----------
  - type: pserv
    name: motionfalcon-postgres
    runtime: postgres
    plan: starter
    disk:
      name: data
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
    envVars:
      - key: POSTGRES_USER
        value: motionfalcon
      - key: POSTGRES_DB
        value: motionfalcon

  # ---------- Backend (FastAPI) ----------
  - type: web
    name: motionfalcon-backend
    env: python
    rootDir: crypto-backend
    plan: starter
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    preDeployCommand: |
      alembic upgrade head
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: motionfalcon-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://motionfalcon-frontend.onrender.com
      # Razorpay (add via dashboard)
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  # ---------- Frontend (React + Vite) ----------
  - type: web
    name: motionfalcon-frontend
    env: static
    rootDir: crypto-frontend
    plan: starter
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://motionfalcon-backend.onrender.com
      - key: VITE_APP_ENV
        value: production 