services:
  # Backend API Service
  - type: web
    name: motionfalcon-backend
    env: python
    plan: starter
    rootDir: crypto-backend
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Static Site
  - type: web
    name: motionfalcon-frontend
    env: static
    plan: starter
    rootDir: crypto-frontend
    buildCommand: |
      npm ci --legacy-peer-deps
      npm run build
      echo "Build completed. Contents of dist directory:"
      ls -la dist/
      echo "Current working directory:"
      pwd
      echo "Verifying dist directory exists:"
      test -d dist && echo "dist directory exists" || echo "dist directory does not exist"
      echo "Copying dist contents to root for alternative deployment:"
      cp -r dist/* ./
      echo "Root directory contents after copy:"
      ls -la
    staticPublishPath: .
    envVars:
      - key: VITE_API_URL
        value: https://motionfalcon-backend.onrender.com
      - key: VITE_APP_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    autoDeploy: true

databases:
  - name: motionfalcon-db
    databaseName: motionfalcon
    user: motionfalcon_user
    plan: starter 