services:
  # --- Backend API (FastAPI) ---
  - type: web
    name: motionfalcon-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: |
      alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    workingDirectory: crypto-backend
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://crypto-frontend.onrender.com
      - key: PYTHONUNBUFFERED
        value: "1"
      # Razorpay (set manually in dashboard)
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false

  # --- Frontend (React + Vite) ---
  - type: web
    name: crypto-frontend
    env: static
    buildCommand: |
      npm ci
      npm run build
    publishPath: dist
    workingDirectory: crypto-frontend
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        value: https://motionfalcon-backend.onrender.com
      - key: VITE_APP_ENV
        value: production

databases:
  - name: crypto-db
    databaseName: crypto
    user: crypto
    plan: free
