services:
  - type: web
    name: motionfalcon-backend-v2
    env: python
    rootDir: crypto-backend
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python startup.py"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: "https://crypto-frontend-lffc.onrender.com,https://motionfalcon-frontend.onrender.com,http://localhost:3000,http://localhost:5173"
      - key: ENVIRONMENT
        value: "production"
      - key: RENDER
        value: "true"
      - key: FORCE_REDEPLOY
        value: "2024-01-01-1704067200"
      - key: REDEPLOY_TRIGGER
        value: "cors-v1-allow-all"

  - type: static
    name: crypto-frontend
    rootDir: crypto-frontend
    region: oregon
    buildCommand: "npm install && npm run build"
    publishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://motionfalcon-backend.onrender.com"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html


databases:
  - name: crypto-db
    plan: free
    region: oregon

  